Program
    DeclList
        funcDef
            VOID
            ID
            formals
                LPAREN
                RPAREN
            funcBody
                LCURLY
                DeclList
                    varDecl
                        INT
                        ID
                        SEMICOLON
                    varDecl
                        INT
                        ID
                        SEMICOLON
                    varDecl
                        INT
                        ID
                        SEMICOLON
                    varDecl
                        INT
                        ID
                        SEMICOLON
                StmtList
                    assignStmt
                        ID
                        ID
                        DIVIDE
                        ID
                    assignStmt
                        ID
                        ID
                        TIMES
                        ID
                    assignStmt
                        ID
                        ID
                        PLUS
                        MINUS
                        ID
                RCURLY
