Program
    DeclList
        varDecl
            INT
            ID
            LSQBRACKET
            INTLITERAL (500)
            RSQBRACKET
            SEMICOLON
        funcDecl
            VOID
            ID
            formals
                LPAREN
                formalDecl
                    INT
                    ID
                formalDecl
                    INT
                    ID
                RPAREN
            SEMICOLON
        funcDecl
            VOID
            ID
            formals
                LPAREN
                formalDecl
                    INT
                    ID
                formalDecl
                    INT
                    ID
                RPAREN
            SEMICOLON
        funcDef
            VOID
            ID
            formals
                LPAREN
                formalDecl
                    INT
                    ID
                formalDecl
                    INT
                    ID
                RPAREN
            funcBody
                LCURLY
                DeclList
                    varDecl
                        INT
                        ID
                        SEMICOLON
                StmtList
                    assignStmt
                        ID
                        arrayExpr
                            ID
                            LSQBRACKET
                            ID
                            RSQBRACKET
                    assignStmt
                        arrayExpr
                            ID
                            LSQBRACKET
                            ID
                            RSQBRACKET
                        arrayExpr
                            ID
                            LSQBRACKET
                            ID
                            RSQBRACKET
                    assignStmt
                        arrayExpr
                            ID
                            LSQBRACKET
                            ID
                            RSQBRACKET
                        ID
                RCURLY
        funcDef
            VOID
            ID
            formals
                LPAREN
                formalDecl
                    INT
                    ID
                formalDecl
                    INT
                    ID
                RPAREN
            funcBody
                LCURLY
                DeclList
                    varDecl
                        INT
                        ID
                        SEMICOLON
                    varDecl
                        INT
                        ID
                        SEMICOLON
                StmtList
                    assignStmt
                        ID
                        ID
                        PLUS
 INTLITERAL (1)
                    assignStmt
                        ID
                        ID
                    callStmt
                        ID
                        LPAREN
                        actualList
                            ID
                            ID
                            PLUS
                            ID
                            DIVIDE
 INTLITERAL (2)
                        RPAREN
                        SEMICOLON
                    whileStmt
                        WHILE
                        LPAREN
                        ID
                        LESSEQ
                        ID
                        RPAREN
                        LCURLY
                        DeclList
                        StmtList
                            whileStmt
                                WHILE
                                LPAREN
                                arrayExpr
                                    ID
                                    LSQBRACKET
                                    ID
                                    RSQBRACKET
                                LESS
                                arrayExpr
                                    ID
                                    LSQBRACKET
                                    ID
                                    RSQBRACKET
                                RPAREN
                                LCURLY
                                DeclList
                                StmtList
                                    assignStmt
                                        ID
                                        ID
                                        PLUS
 INTLITERAL (1)
                                RCURLY
                            whileStmt
                                WHILE
                                LPAREN
                                arrayExpr
                                    ID
                                    LSQBRACKET
                                    ID
                                    RSQBRACKET
                                LESS
                                arrayExpr
                                    ID
                                    LSQBRACKET
                                    ID
                                    RSQBRACKET
                                RPAREN
                                LCURLY
                                DeclList
                                StmtList
                                    assignStmt
                                        ID
                                        ID
                                        MINUS
 INTLITERAL (1)
                                RCURLY
                            ifElseStmt
                                IF
                                LPAREN
                                ID
                                LESS
                                ID
                                RPAREN
                                LCURLY
                                DeclList
                                StmtList
                                    callStmt
                                        ID
                                        LPAREN
                                        actualList
                                            ID
                                            ID
                                        RPAREN
                                        SEMICOLON
                                    assignStmt
                                        ID
                                        ID
                                        PLUS
 INTLITERAL (1)
                                    assignStmt
                                        ID
                                        ID
                                        PLUS
 INTLITERAL (1)
                                RCURLY
                                ELSE
                                LCURLY
                                DeclList
                                StmtList
                                    callStmt
                                        ID
                                        LPAREN
                                        actualList
                                            ID
                                            ID
                                        RPAREN
                                        SEMICOLON
                                    assignStmt
                                        ID
                                        ID
                                        PLUS
 INTLITERAL (1)
                                    assignStmt
                                        ID
                                        ID
                                        PLUS
 INTLITERAL (1)
                                RCURLY
                        RCURLY
                    callStmt
                        ID
                        LPAREN
                        actualList
                            ID
                            ID
                        RPAREN
                        SEMICOLON
                    ifStmt
                        IF
                        LPAREN
                        ID
                        LESS
                        ID
                        MINUS
 INTLITERAL (1)
                        RPAREN
                        LCURLY
                        DeclList
                        StmtList
                            callStmt
                                ID
                                LPAREN
                                actualList
                                    ID
                                    ID
                                    MINUS
 INTLITERAL (1)
                                RPAREN
                                SEMICOLON
                        RCURLY
                    ifStmt
                        IF
                        LPAREN
                        ID
                        PLUS
 INTLITERAL (1)
                        LESS
                        ID
                        RPAREN
                        LCURLY
                        DeclList
                        StmtList
                            callStmt
                                ID
                                LPAREN
                                actualList
                                    ID
                                    PLUS
 INTLITERAL (1)
                                    ID
                                RPAREN
                                SEMICOLON
                        RCURLY
                RCURLY
        funcDef
            VOID
            ID
            formals
                LPAREN
                RPAREN
            funcBody
                LCURLY
                DeclList
                    varDecl
                        INT
                        ID
                        SEMICOLON
                    varDecl
                        INT
                        ID
                        SEMICOLON
                StmtList
                    assignStmt
                        ID
 INTLITERAL (500)
                    ifStmt
                        IF
                        LPAREN
                        ID
                        GREATEREQ
 INTLITERAL (2)
                        RPAREN
                        LCURLY
                        DeclList
                            varDecl
                                INT
                                ID
                                SEMICOLON
                        StmtList
                            assignStmt
                                ID
 INTLITERAL (0)
                            forStmt
                                FOR
                                LPAREN
                                assignStmt
                                    ID
 INTLITERAL (1)
                                SEMICOLON
                                ID
                                LESS
                                ID
                                SEMICOLON
                                assignStmt
                                    ID
                                    ID
                                    PLUS
 INTLITERAL (1)
                                RPAREN
                                LCURLY
                                DeclList
                                StmtList
                                    ifStmt
                                        IF
                                        LPAREN
                                        arrayExpr
                                            ID
                                            LSQBRACKET
                                            ID
                                            RSQBRACKET
                                        LESS
                                        arrayExpr
                                            ID
                                            LSQBRACKET
                                            ID
                                            RSQBRACKET
                                        RPAREN
                                        LCURLY
                                        DeclList
                                        StmtList
                                            assignStmt
                                                ID
                                                ID
                                        RCURLY
                                RCURLY
                            callStmt
                                ID
                                LPAREN
                                actualList
                                    ID
                                    MINUS
 INTLITERAL (1)
                                    ID
                                RPAREN
                                SEMICOLON
                            callStmt
                                ID
                                LPAREN
                                actualList
 INTLITERAL (0)
                                    ID
                                    MINUS
 INTLITERAL (2)
                                RPAREN
                                SEMICOLON
                        RCURLY
                RCURLY
